// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmKXqQXl62WC3oA__cDvDmBd7y_wPmwCU',
    appId: '1:228241827067:web:ead313446c90be00963c5e',
    messagingSenderId: '228241827067',
    projectId: 'tracetnotes',
    authDomain: 'tracetnotes.firebaseapp.com',
    storageBucket: 'tracetnotes.appspot.com',
    measurementId: 'G-1DZECLC8S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKzLIohAZiULTengMb7CGsnfqo6LN3jA',
    appId: '1:228241827067:android:7123e2a45c086ff3963c5e',
    messagingSenderId: '228241827067',
    projectId: 'tracetnotes',
    storageBucket: 'tracetnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5DfxFYsDndPJNlqKnxm8kBcAen0D8mNI',
    appId: '1:228241827067:ios:bbd48cc3655fe4ad963c5e',
    messagingSenderId: '228241827067',
    projectId: 'tracetnotes',
    storageBucket: 'tracetnotes.appspot.com',
    iosBundleId: 'com.example.learningDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5DfxFYsDndPJNlqKnxm8kBcAen0D8mNI',
    appId: '1:228241827067:ios:d2116d218d7586c2963c5e',
    messagingSenderId: '228241827067',
    projectId: 'tracetnotes',
    storageBucket: 'tracetnotes.appspot.com',
    iosBundleId: 'com.example.learningDart.RunnerTests',
  );
}
